### ISSUE TITLE
Add the possibility to exclude specific gpu's

### ISSUE THREAD

**Issue by robvanmieghem** [robvanmieghem/gominer#1]

**Comment by robvanmieghem** [comment]
I've been thinking on how to indicate which gpu to exclude and there are several options, not sure which one is best.
Options:
* opencl platform + index:
 * pro: is the same as the official miner
 * con: you don't know it if you are not able to list them first, is also in a weir `0:1` or something like that format
* pci bus id
 * pro: predictable
 * con: most people don't know how to list the id's on the pci bus
* just number them 0-n
 * pro: simple and is the the same as option 1 except that the numbering continues instead of indicating the platform index
 * con: is an arbitrary numbering, need a special gominer command to show the indexes of all the gpu's

Proposal: go for the last option to just number them 0-n

**Comment by pmknutsen** [comment]
I'm in favor on the last option too. Why an option to exclude vs which to include (which is more 'normal')?

**Comment by robvanmieghem** [comment]
@pmknutsen I think it is more convenient to just use all available gpu's instead of specifyig which ones to use. The case where you want to exclude is because of a broken gpu, exclude an on board one used by your monitor,....
