### ISSUE TITLE
Win10 gominer.exe with high CPU usage

### ISSUE THREAD

**Issue by c3msu** [robvanmieghem/gominer#11]
Hi,

Thanks for your win version gominer.exe. I tried it with my RX480 rig and it works very well. However, i have another one with nvidia GTX1070. It also works but just one difference. CPU usage is 100% which is fast higher than the other one(5%).

CPU is i3-4150t which includes a embeded video core. But I disable it in command line with -E option. In screen output it also shows nvidia cuda platform with all 1070 and no available Intel OpenCL device found. So it shouldn't use CPU for mining. But it does look like CPU is fully loaded with computational task.

This is very strange and I hope you can help me. Thanks.

**Comment by robvanmieghem** [comment]
This is a flaw in the nvidia driver for opencl. All miners using opencl (not just for sia) have this behaviour.
