### ISSUE TITLE
miner.minerCount doesn't take into consideration excluded GPU

### ISSUE THREAD

**Issue by antoninblanc** [robvanmieghem/gominer#12]
In miner.go, `nrOfMiningDevices` is defined as `nrOfMiningDevices := len(clDevices)` then few lines after, the for loop handle `deviceExcludedForMining`.

This cause incorrect work.Offset

`				work.Offset += uint64(miner.GlobalItemSize) * uint64(miner.minerCount)
`

Sorry for not giving a push request, first time i read Go code !

**Comment by robvanmieghem** [comment]
Can you point me to the exact line of code where you see `work.Offset += uint64(miner.GlobalItemSize) * uint64(miner.minerCount) ` ? 

I have a suspicion you are reading the code from a fork that has been modified in a suboptimal way.

**Comment by antoninblanc** [comment]
uups my bad, indeed wrong github depot. it was refering to this fork https://github.com/SiaMining/gominer/blob/poolmod3/miner.go#L104

for info you have a pool request https://github.com/robvanmieghem/gominer/pull/10 with the that code https://github.com/robvanmieghem/gominer/pull/10/commits/07c53416dc7fe2eb05bfb0f3d38772b7aeba42ca#diff-02219c16ae62ec873619f6118d759f1bR104

**Comment by robvanmieghem** [comment]
@antoninblanc looks like they turned that off in the repository settings
