### ISSUE TITLE
Unknown opencl version

### ISSUE THREAD

**Issue by faddat** [robvanmieghem/gominer#19]
When trying to start gominer, I'm told there's no version number for opencl available to it.  Any thoughts?

**Comment by robvanmieghem** [comment]
@faddat Can you paste the exact output you get?

**Comment by faddat** [comment]
Sure-- and please know that after updating gominer, I've found that while it is still giving me the unknown opencl message, it now works.  

gominer: /opt/cuda/lib64/libOpenCL.so.1: no version information available (required by gominer)
gominer: /opt/cuda/lib64/libOpenCL.so.1: no version information available (required by gominer)
gominer: /opt/cuda/lib64/libOpenCL.so.1: no version information available (required by gominer)
