### ISSUE TITLE
Show the running average hashing rate

### ISSUE THREAD

**Issue by pmknutsen** [robvanmieghem/gominer#2]
Currently, only the instantaneous hashing rate is displayed per GPU. It would be useful to also show the average hashing rate (per GPU, or averaged across GPU) from when gominer was launched to present (i.e. the running average: (previous cycle + current cycle) / 2).

**Comment by robvanmieghem** [comment]
Normally, this does not change and since almost no-one is solo-mining anymore, the poolsoftware gives running averages per rig, closing this issue.
