### ISSUE TITLE
undefined reference to `cl....'

### ISSUE THREAD

**Issue by bonswouar** [robvanmieghem/gominer#21]
Trying to use it on windows, had few troubles installing OpenCL (had the same error than #7 at first).
But now I'm getting :

> C:\Users\BONSWO~1\AppData\Local\Temp\go-build107753098\github.com\robvanmieghem\go-opencl\cl_obj\context.cgo2.o: In function `_cgo_bddfa6838c48_Cfunc_clCreateBuffer':
> C:/Go/projects/src/github.com/robvanmieghem/go-opencl/cl/context.go:55: undefined reference to`clCreateBuffer'
> C:\Users\BONSWO~1\AppData\Local\Temp\go-build107753098\github.com\robvanmieghem\go-opencl\cl_obj\context.cgo2.o: In function `_cgo_bddfa6838c48_Cfunc_clCreateCommandQueue':
> C:/Go/projects/src/github.com/robvanmieghem/go-opencl/cl/context.go:75: undefined reference to`clCreateCommandQueue'
> C:\Users\BONSWO~1\AppData\Local\Temp\go-build107753098\github.com\robvanmieghem\go-opencl\cl_obj\context.cgo2.o: In function `_cgo_bddfa6838c48_Cfunc_clCreateContext':
> C:/Go/projects/src/github.com/robvanmieghem/go-opencl/cl/context.go:98: undefined reference to`clCreateContext'
> C:\Users\BONSWO~1\AppData\Local\Temp\go-build107753098\github.com\robvanmieghem\go-opencl\cl_obj\context.cgo2.o: In function `_cgo_bddfa6838c48_Cfunc_clCreateProgramWithSource':
> C:/Go/projects/src/github.com/robvanmieghem/go-opencl/cl/context.go:120: undefined reference to`clCreateProgramWithSource'
> C:\Users\BONSWO~1\AppData\Local\Temp\go-build107753098\github.com\robvanmieghem\go-opencl\cl_obj\context.cgo2.o: In function `_cgo_bddfa6838c48_Cfunc_clCreateUserEvent':
> C:/Go/projects/src/github.com/robvanmieghem/go-opencl/cl/context.go:138: undefined reference to`clCreateUserEvent'

And many more...

It looks like OpenCL isn't properly loaded, what could I miss ?!

**Comment by robvanmieghem** [comment]
make sure the library path environment variable is set properly
