### ISSUE TITLE
Cannot link to OpenCL

### ISSUE THREAD

**Issue by Steve1943** [robvanmieghem/gominer#22]
On Windows10 my attempted installation of "gominer" fails because the link editor (loader) "ld.exe" cannot find "OpenCl"

Github download seems fine.  Problem manifests identically with "git get" or "git install"
 
64bit "gcc.exe" is found and seems to work now - 
(after a struggle and installation of TDM-GCC-64 to provide a compatible/stable 64bit GNU C-compiler for Windoows10).

I have CL headers in system PATH to both Intel_SDKv6.3/OpenCL and to "mingw64\include\CL" which both contain OpenCL headers for both "cl.h" and "opencl.h" 

Is it a a bug or am I missing something?

See console evidence cited below:

 Directory of C:\msys64\mingw64\include\CL

14/06/2016  08:02    <DIR>          .
14/06/2016  08:02    <DIR>          ..
14/06/2016  08:02            74,542 cl.h
14/06/2016  08:02           312,299 cl.hpp
14/06/2016  08:02           299,451 cl2.hpp
14/06/2016  08:02             5,122 cl_d3d10.h
14/06/2016  08:02             5,116 cl_d3d11.h
14/06/2016  08:02             5,421 cl_dx9_media_sharing.h
14/06/2016  08:02             5,358 cl_egl.h
14/06/2016  08:02            16,368 cl_ext.h
14/06/2016  08:02             7,583 cl_gl.h
14/06/2016  08:02             2,869 cl_gl_ext.h
14/06/2016  08:02            43,544 cl_platform.h
14/06/2016  08:02             1,993 opencl.h
              12 File(s)        779,666 bytes
               2 Dir(s)  17,493,184,512 bytes free

C:\msys64\mingw64\include\CL>go install github.com/robvanmieghem/gominer
# github.com/robvanmieghem/go-opencl/cl
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lOpenCL
collect2.exe: error: ld returned 1 exit status

**Comment by robvanmieghem** [comment]
@Steve1943 Please make sure your include and library paths are set correctly, it is not because you installed the opencl sdk that it means those paths are added to the environment. In my case (compiling on virtualbox and with the intel sdk in a powershell) this means executing the following command before executing `go build`:
`$env:LIBRARY_PATH = "C:\Program Files (x86)\Intel\OpenCL SDK\lib\x64"`

**Comment by Steve1943** [comment]
Rob - thanks a million for your help - it's really helpful and much 
appreciated.  Steve

------ Original Message ------

**Comment by robvanmieghem** [comment]
@Steve1943 Your welcome, did you manage to get the linker to work now?
