### ISSUE TITLE
I am a novice, want to learn to dig sia, but now encounter a problem.

### ISSUE THREAD

**Issue by dragon201** [robvanmieghem/gominer#24]
1. Now I opened the Sia-UI.exe2. Open the sia-gpu-1.0.5 inside the sia-gpu-miner.exe But did prompt http error 404 wrong, unable to connect to the server, how to solve? Thank you

**Comment by hunterj12** [comment]
having the same issue

**Comment by robvanmieghem** [comment]
The sia-gpu-miner is different software but it functions through the same interface as gominer does. You have to run `siad` with the miner module enabled.
