### ISSUE TITLE
Big decrease in hash rate with new kernel

### ISSUE THREAD

**Issue by Fornax96** [robvanmieghem/gominer#3]
So I swapped out the kernel of @bitspill's pool gominer with this one: https://github.com/robvanmieghem/gominer/commit/8056519afd8f659991115b3f888b120049d73480.

The hash rate with the old kernel at intensity 24 was steady at 222 MH/s. 
Now with the new one it shows 155 MH/s, also at intensity 24.

Setting the intensity higher than 24 changes nothing. During all tests the nvidia control panel displayed 99% GPU usage.

My card is a MSI Nvidia GeForce GTX 660 (This one, specifically: https://www.msi.com/Graphics-card/N660_TF_2GD5OC.html#hero-overview)
My CPU is Intel® Core™ i5-4690K CPU @ 3.50GHz × 4 
OS: Ubuntu 15.10 x86_64

**Comment by robvanmieghem** [comment]
@Fornax96 No offense but I am closing this issue as nvidia cards perform a lot better with the cudaminer and opencl improvements mostly benefit amd cards.
