### ISSUE TITLE
Error opening consensus database: cannot allocate memory

### ISSUE THREAD

**Issue by Granitoid** [robvanmieghem/gominer#4]
Mar 24 11:34:27 siad[2028]: Loading...
Mar 24 11:34:27 siad[2028]: (1/7) Loading gateway...
Mar 24 11:34:28 siad[2028]: (2/7) Loading consensus...
Mar 24 11:34:28 siad[2028]: error opening consensus database: cannot allocate memory
Mar 24 11:34:28 systemd[1]: sia.service: main process exited, code=exited, status=1/FAILURE
Mar 24 11:34:28 systemd[1]: Unit sia.service entered failed state.

$ free -h
             total       used       free     shared    buffers     cached
Mem:          1,7G       184M       1,5G         9M        11M        97M
-/+ buffers/cache:        76M       1,7G
Swap:         3,7G         0B       3,7G

$ ls -lA /home/sia/consensus
-rw------- 1 sia sia 2147483647 Mar 24 11:34 consensus.db

Source:
https://github.com/NebulousLabs/Sia-UI/releases/download/v0.5.1-beta/Sia-UI-linux-ia32.tar.gz

OS:
Linux version 3.16.0-4-amd64 (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.7-ckt20-1+deb8u1 (2015-12-14)

**Comment by robvanmieghem** [comment]
@Granitoid shouldn't this issue be created in the https://github.com/NebulousLabs/Sia project?

**Comment by Granitoid** [comment]
Excuse

**Comment by robvanmieghem** [comment]
@Granitoid no worries
